from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('kso',
                       (r'^concert/(?P<member>m/)?$', 'concertViews.concertDetail', {"concert_id": "next"}),
                       (r'^concert/(?P<concert_id>\d+)/(?P<member>m/)?$', 'concertViews.concertDetail'),
                       (r'^concert\.(?P<concert_id>\d+)(?P<member>\.m)?.ics$', 'concertViews.downloadConcert'),
                       (r'^concert/(?P<year>\d{4})/(?P<month>\d{2})/(?P<member>m/)?$', 'concertViews.concertDetail'),
                       (r'^venue/(?P<venue_id>\d+)/(?P<member>m/)?$', 'otherViews.venueDetail'),
                       (r'^season/(?P<member>m/)?$', 'seasonViews.seasonDetail', {"season_id": "this"}),
                       (r'^season/next/(?P<member>m/)?$', 'seasonViews.seasonDetail', {"season_id": "next"}),
                       (r'^season/(?P<season_id>\d+)/(?P<member>m/)?$', 'seasonViews.seasonDetail'),
                       (r'^season\.(?P<season_id>\d+)(?P<member>\.m)?.ics$', 'seasonViews.downloadSeason'),
                       (r'^whereto/', 'otherViews.whereTo'),
                       (r'^shop/', 'otherViews.shop'),
                       (r'^(?P<member>m/)?$', 'otherViews.home'),
                       (r'^mailinglist/', 'otherViews.mailingList'),
                       (r'^archive/(?P<member>m/)?$', 'otherViews.archive'),
                       (r'^programmes/(?P<member>m/)?$', 'otherViews.programmes'),
                       (r'^download/(?P<file>.*)$', 'otherViews.download'),
                       (r'^listen/(?P<member>m/)?$', 'otherViews.listen'),
                       (r'^thanks/', 'otherViews.thanks'),
                       (r'^gallery/(?P<member>m/)?$', 'otherViews.gallery'),
                       (r'^members/(?P<member>m/)?$', 'memberViews.members'),
                       (r'^member/(?P<member_id>\d+)/(?P<member>m/)?$', 'memberViews.memberDetail'),
                       (r'^technical/', 'siteViews.technical'),
                       (r'^conductor/(?P<conductor_id>\d+)/(?P<member>m/)?$', 'otherViews.conductorDetail'),
                       (r'^conductor/(?P<member>m/)?$', 'otherViews.conductorDetail', {"conductor_id": 1}),
                       (r'^composer/(?P<composer_id>\d+)/(?P<member>m/)?$', 'otherViews.composerDetail'),
                       (r'^soloist/(?P<soloist_id>\d+)/(?P<member>m/)?$', 'otherViews.soloistDetail'),
                       (r'^sjss/(?P<member>m/)?$', 'otherViews.venueDetail', {"venue_id": "2"}),
                       (r'^qeh/(?P<member>m/)?$', 'otherViews.venueDetail', {"venue_id": "1"}),
                       (r'^cadogan/(?P<member>m/)?$', 'otherViews.venueDetail', {"venue_id": "22"}),
                       (r'^milton/(?P<member>m/)?$', 'otherViews.venueDetail', {"venue_id": "60"}),
                       (r'^pimlico/(?P<member>m/)?$', 'otherViews.venueDetail', {"venue_id": "31"}),
                       (r'^henrywood/(?P<member>m/)?$', 'otherViews.venueDetail', {"venue_id": "14"}),
                       (r'^(?P<page_name>[a-z]+)/(?P<member>m/)?$', 'otherViews.specialPage'),
)
